# Generated by Django 5.2.4 on 2025-07-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cartmodel_dt_finalized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='dt_finalized',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
