# Generated by Django 5.2.4 on 2025-07-07 17:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cartmodel_dt_finalized'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartmodel',
            unique_together={('user',)},
        ),
    ]
