# Generated by Django 5.2.4 on 2025-07-08 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cartmodel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartmodel',
            unique_together=set(),
        ),
    ]
